# Generated by Django 3.2.2 on 2021-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=96058, editable=False),
        ),
    ]
