# Generated by Django 3.2.2 on 2021-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_alter_linkpayment_sec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=81203, editable=False),
        ),
    ]
