# Generated by Django 3.2.2 on 2021-06-07 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_linkpayment_sec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsaving',
            name='description',
            field=models.TextField(blank=True, help_text='Add a description if you like, here', null=True, validators=[django.core.validators.MinValueValidator(25, 'At least write 25 characters')]),
        ),
        migrations.AlterField(
            model_name='goalsaving',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goalsaving',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/goals/images/'),
        ),
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=63516, editable=False),
        ),
        migrations.CreateModel(
            name='Monthlies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('CHAR', 'Charged'), ('FAIL', 'Failed'), ('ABOR', 'Aborted')], max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountmonthlies', to='cuenta.cuenta')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthlies', to='cuenta.goalsaving')),
            ],
        ),
    ]
