# Generated by Django 3.2.2 on 2021-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_auto_20210607_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalsaving',
            name='achieved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalsaving',
            name='description',
            field=models.TextField(blank=True, help_text='Add a description if you like, here', null=True),
        ),
        migrations.AlterField(
            model_name='goalsaving',
            name='monthly',
            field=models.PositiveIntegerField(blank=True, help_text='Want to add a monthly topup amount? Leave at 0 if not.', null=True),
        ),
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=87740, editable=False),
        ),
    ]
