# Generated by Django 3.2.4 on 2021-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0008_alter_linkpayment_sec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=83160, editable=False),
        ),
    ]
