# Generated by Django 3.2.4 on 2021-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_alter_linkpayment_sec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=25204, editable=False),
        ),
    ]
