# Generated by Django 3.2.4 on 2021-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_alter_linkpayment_sec_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpayment',
            name='sec_code',
            field=models.PositiveSmallIntegerField(default=11576, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TopUp', 'TopUp'), ('Donation', 'Donation'), ('LinkPayment', 'LinkPayment'), ('ToGoal', 'Added to Goal')], max_length=11),
        ),
    ]
