# Generated by Django 3.2.2 on 2021-05-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saver',
            name='validated',
        ),
        migrations.AddField(
            model_name='saver',
            name='validation_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('VALIDATION_ASKED', 'Validation asked'), ('VALIDATED', 'Validated'), ('REFUSED', 'Refused'), ('OUT_OF_DATE', 'Out of Date')], default='CREATED', max_length=17),
        ),
    ]
