# Generated by Django 3.2 on 2021-05-06 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saver', '0001_initial'),
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.PositiveIntegerField(default=0)),
                ('expiration_date', models.PositiveSmallIntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('alias', models.CharField(default='', max_length=20)),
                ('provider', models.CharField(default='', max_length=15)),
                ('card_type', models.CharField(choices=[('CB_VISA_MASTERCARD', 'CB VISA MASTERCARD'), ('MAESTRO', 'Maestro'), ('DINERS', 'Diners'), ('AMEX', 'Amex'), ('MASTERPASS', 'Masterpass'), ('P24', 'P24'), ('IDEAL', 'Ideal'), ('PAYLIB', 'Paylib'), ('BCMC', 'Bcmc')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('creation_date', models.PositiveIntegerField(default=0)),
                ('fingerprint', models.CharField(default='call update function', max_length=100)),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangocard', to='saver.saver')),
            ],
        ),
        migrations.CreateModel(
            name='MangoLegalUser',
            fields=[
                ('saver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saver.saver')),
                ('legal_type', models.CharField(choices=[('BUSINESS', 'Business'), ('ORGANIZATION', 'Organization'), ('SOLETRADER', 'Soletrader')], max_length=35)),
                ('legal_name', models.CharField(max_length=150)),
                ('legal_rep_email', models.EmailField(max_length=254, null=True)),
                ('company_number', models.CharField(max_length=150, null=True)),
            ],
            bases=('saver.saver',),
        ),
        migrations.CreateModel(
            name='MangoNaturalUser',
            fields=[
                ('saver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='saver.saver')),
            ],
            bases=('saver.saver',),
        ),
        migrations.CreateModel(
            name='MangoPayIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piid', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('culture', models.CharField(default='EN', max_length=2)),
                ('statement_descriptor', models.CharField(default='', max_length=12)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('VALIDATED', 'Validated')], default='CREATED', max_length=9)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(default='', max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='MangoPreAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MangoBankWirePayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.mangopayin')),
                ('execution_type', models.CharField(max_length=50)),
                ('wire_reference', models.CharField(max_length=50)),
                ('wire_type', models.CharField(max_length=5)),
                ('iban', models.CharField(max_length=50)),
                ('bic', models.CharField(max_length=25)),
            ],
            bases=('payment.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoCardDirectPayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.mangopayin')),
            ],
            bases=('payment.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoCardWebPayIn',
            fields=[
                ('mangopayin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.mangopayin')),
                ('return_url', models.URLField(blank=True, null=True)),
                ('card_type', models.CharField(choices=[('CB_VISA_MASTERCARD', 'CB VISA MASTERCARD'), ('MAESTRO', 'Maestro'), ('DINERS', 'Diners'), ('AMEX', 'Amex'), ('MASTERPASS', 'Masterpass'), ('P24', 'P24'), ('IDEAL', 'Ideal'), ('PAYLIB', 'Paylib'), ('BCMC', 'Bcmc')], default='CB_VISA_MASTERCARD', max_length=20)),
                ('secure_mode', models.BooleanField(default=True)),
            ],
            bases=('payment.mangopayin',),
        ),
        migrations.CreateModel(
            name='MangoWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_wallet', to='cuenta.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MangoTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[], max_length=9, null=True)),
                ('execution_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'USD'), ('CHF', 'Swiss Franc')], default='EUR', max_length=3)),
                ('credited_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transfercreditedaccount', to='cuenta.cuenta')),
                ('debited_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transferdebitedaccount', to='cuenta.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='MangoPayOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poid', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('culture', models.CharField(default='EN', max_length=2)),
                ('statement_descriptor', models.CharField(default='', max_length=12)),
                ('result_code', models.CharField(blank=True, max_length=6, null=True)),
                ('result_message', models.CharField(blank=True, max_length=255, null=True)),
                ('nature', models.CharField(default='', max_length=10)),
                ('transaction_type', models.CharField(max_length=10)),
                ('bank_wire_ref', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayout_mangopayout_author', to='saver.saver')),
                ('dwid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayout_mangopayout_dwid', to='payment.mangowallet')),
            ],
        ),
        migrations.AddField(
            model_name='mangopayin',
            name='cwid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayin_mango_payin_cwid', to='payment.mangowallet'),
        ),
        migrations.AddField(
            model_name='mangopayin',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mangopayin_mango_payin_author', to='saver.saver'),
        ),
        migrations.CreateModel(
            name='MangoCardRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crid', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('card_type', models.CharField(default='CB VISA MASTERCARD', max_length=20)),
                ('card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangocardregistration', to='payment.mangocard')),
            ],
        ),
        migrations.CreateModel(
            name='MangoBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveIntegerField()),
                ('bank_account_type', models.CharField(default='IBAN', max_length=6)),
                ('al1', models.CharField(max_length=150)),
                ('al2', models.CharField(max_length=150)),
                ('pc', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=50)),
                ('bic', models.CharField(max_length=12)),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='saverbankaccount', to='saver.saver')),
            ],
        ),
    ]
