# Generated by Django 3.2.2 on 2021-05-10 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saver', '0002_auto_20210510_2208'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangopayout',
            name='author',
        ),
        migrations.AddField(
            model_name='mangopayout',
            name='saver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='savermangopayout', to='saver.saver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangotransfer',
            name='saver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='savertransfer', to='saver.saver'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangobankaccount',
            name='bic',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mangobankaccount',
            name='bid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mangopayout',
            name='dwid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dwidmangopayout', to='payment.mangowallet'),
        ),
        migrations.AlterField(
            model_name='mangotransfer',
            name='status',
            field=models.CharField(blank=True, default='Paid', max_length=9, null=True),
        ),
    ]
