# Generated by Django 3.2.2 on 2021-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210513_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangobankaccount',
            name='city',
            field=models.CharField(default='premigraiton', max_length=50),
            preserve_default=False,
        ),
    ]
