# Generated by Django 3.2.2 on 2021-05-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_mangobankaccount_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangobankaccount',
            name='currency',
            field=models.CharField(default=(('EUR', 'Euro'), ('USD', 'USD'), ('CHF', 'Swiss Franc')), max_length=3),
        ),
        migrations.AlterField(
            model_name='mangopayout',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
