# Generated by Django 3.2.2 on 2021-05-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210514_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangobankaccount',
            old_name='iban',
            new_name='account_number',
        ),
    ]
