# Generated by Django 3.2.4 on 2021-06-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20210613_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangocardwebpayin',
            name='return_url',
            field=models.URLField(default='http'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mangocardwebpayin',
            name='secure_mode',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('FORCE', 'Force'), ('NO_CHOICE', 'No_Choice')], default='Default', max_length=9),
        ),
    ]
