# Generated by Django 3.2.4 on 2021-06-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210621_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangobankaccount',
            name='iban',
            field=models.CharField(default='filler', max_length=25),
            preserve_default=False,
        ),
    ]
