# Generated by Django 3.2.4 on 2021-06-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_mangobankaccount_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangopayin',
            name='tag',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
